language: scala
script: 
  - sbt compile test:compile
  - sbt -Dakka.test.timefactor=1.5 'set concurrentRestrictions in Global += Tags.limit(Tags.Test, 1)' test
scala:
  - 2.9.3
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  email:
    - johannes@spray.io
    - mathias@spray.io
