language: scala
script: 
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
  - sbt ++$TRAVIS_SCALA_VERSION -Dakka.test.timefactor=1.5 'set concurrentRestrictions in Global += Tags.limit(Tags.Test, 1)' test
scala:
  - 2.10.1
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/notifications/ to learn more
  # about configuring notification recipients and more (e.g. IRC notifications).
  email: false
